# Generated by Django 5.2.7 on 2026-01-26 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0016_customfood'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfood',
            name='nutritionist',
            field=models.ForeignKey(blank=True, help_text='Nutricionista proprietário do alimento (nulo para global)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_foods', to=settings.AUTH_USER_MODEL),
        ),
    ]
