# Generated by Django 5.0.2 on 2026-02-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0018_add_dietary_restrictions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('energy_kcal', models.FloatField()),
                ('protein_g', models.FloatField()),
                ('carbs_g', models.FloatField()),
                ('fat_g', models.FloatField()),
                ('fiber_g', models.FloatField(default=0)),
                ('prep_method', models.CharField(choices=[('RAW', 'Cru/In Natura'), ('GRILLED', 'Grelhado'), ('BOILED', 'Cozido'), ('ROASTED', 'Assado'), ('FRIED', 'Frito'), ('SMOKED', 'Defumado'), ('OTHER', 'Outros/Misto')], default='OTHER', max_length=20)),
                ('purity_index', models.CharField(choices=[('STAPLE', 'Comida de Verdade (Single Ingredient)'), ('COMPOSITE', 'Receita/Prato Composto (Multi-Ingredient)'), ('INDUSTRIAL', 'Ultraprocessado/Industrializado')], default='STAPLE', max_length=20)),
                ('processing_level', models.IntegerField(default=1, help_text='Escala NOVA (1=Mínimo, 4=Ultraprocessado)')),
                ('anchor_macro', models.CharField(choices=[('PROTEIN', 'Proteína'), ('CARBS', 'Carboidrato'), ('FAT', 'Gordura'), ('FIBER', 'Fibra'), ('CALORIES', 'Equilíbrio Calórico (Mix)')], default='CALORIES', max_length=20)),
                ('is_cooked', models.BooleanField(default=True)),
                ('source_name', models.CharField(help_text='TACO, TBCA ou USDA', max_length=50)),
                ('source_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alimento Unificado',
                'verbose_name_plural': 'Alimentos Unificados',
            },
        ),
        migrations.RenameIndex(
            model_name='foodsubstitutionrule',
            new_name='foodsub_dietary_idx',
            old_name='diets_foodsub_dietary_idx',
        ),
        migrations.RenameIndex(
            model_name='foodsubstitutionrule',
            new_name='foodsub_orig_vegan_idx',
            old_name='diets_foodsub_orig_vegan_idx',
        ),
        migrations.RenameIndex(
            model_name='foodsubstitutionrule',
            new_name='foodsub_orig_veg_idx',
            old_name='diets_foodsub_orig_veg_idx',
        ),
        migrations.AddIndex(
            model_name='unifiedfood',
            index=models.Index(fields=['name'], name='diets_unifi_name_a18bde_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedfood',
            index=models.Index(fields=['prep_method'], name='diets_unifi_prep_me_c89d76_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedfood',
            index=models.Index(fields=['purity_index'], name='diets_unifi_purity__4b5a14_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedfood',
            index=models.Index(fields=['anchor_macro'], name='diets_unifi_anchor__8debbe_idx'),
        ),
    ]
