# Generated by Django 5.0.2 on 2026-02-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0019_unifiedfood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedfood',
            name='custom_category',
            field=models.CharField(blank=True, help_text='Clã Biológico (CEREAL, PROTEIN, etc)', max_length=50, null=True),
        ),
    ]
