FROM node:20-slim
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
# O Next.js com output: export gera os arquivos em /app/out
# Verificação de segurança e permissão
RUN cd out && ls -la
EXPOSE 3000
CMD ["npm", "start"]
